# jenkins-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-secret
  namespace: devops-tools
spec:
  secretName: jenkins-secret
  privateKey:
    rotationPolicy: Always
  commonName: jenkins.k-tech.cloud
  dnsNames:
    - jenkins.k-tech.cloud
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer